jobs:
  - job: Build_PS_Windows
    pool:
      vmImage: windows-latest
    steps:
    - pwsh: |
        .\Build.ps1 -NonInteractive -NoLogo -NoProfile
      displayName: 'Test'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: always()
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'PS_Windows'

    - task: ArchiveFiles@2
      displayName: 'Archive Build'
      inputs:
        rootFolderOrFile: Build
        includeRootFolder: false
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

  - job: Build_PSCore_Ubuntu
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        pwsh -c '.\Build.ps1' -NonInteractive -NoLogo -NoProfile
      displayName: 'Test'

    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'PSCore_Ubuntu'
      condition: always()
      displayName: 'Publish Test Results'

  - job: Build_PSCore_Mac
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        pwsh -c '.\Build.ps1' -NonInteractive -NoLogo -NoProfile
      displayName: 'Test'

    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'PSCore_MacOS'
      condition: always()
      displayName: 'Publish Test Results'