jobs:
  - job: Build_PS_Win2019
    pool:
      vmImage: windows-2019
    steps:
    - powershell: |
        .\Build.ps1
      displayName: 'Test'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: always()
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'PS_Win2019'

    - task: ArchiveFiles@2
      displayName: 'Archive Build'
      inputs:
        rootFolderOrFile: Build
        includeRootFolder: false
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

  - job: Build_PSCore_Ubuntu1804
    pool:
      vmImage: ubuntu-18.04
    steps:
    - script: |
        pwsh -c '.\Build.ps1'
      displayName: 'Test'

    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'PSCore_Ubuntu1804'
      condition: always()
      displayName: 'Publish Test Results'

  - job: Build_PSCore_MacLatest
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        pwsh -c '.\Build.ps1'
      displayName: 'Test'

    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'PSCore_MacOSLatest'
      condition: always()
      displayName: 'Publish Test Results'